### ISSUE TITLE
Why you run build in postinstall hook?

### ISSUE THREAD

**Issue by CheerlessCloud** [wentout/eslint-plugin-no-arrow-this#1]
It's will be execute on every installation! 🌲
Also, in postinstall hook you can't access to your devDependencies. Yes, it's can work only if your project contain babel and other dependencies on high-level in your node_modules. It's totally wrong practice. And more, I review code and didn't see need for babel at all. 🙄

By best practices your must transpile your code to dist folder (explicitly run npm build in CI or in prepublish hook) and publish only dist folder (see [package.json => files](https://docs.npmjs.com/files/package.json#files)). Also I recommend you use Travis CI and semantic-release, but it to your taste.

If you want, I can create PR in the next few days. 🚀

**Comment by wentout** [comment]
yea, just copy pase
I'll rid of it, for sure

**Comment by wentout** [comment]
dit id 1.1.8
and you need to show me all other stuff with that setting of you mean about
